Hi! I’m **Axel Legay**, a digital consultant based in Belgium 🇧🇪

I work at the crossroads of **technology, clarity, and accessibility** — helping people and projects build smart, visible, and meaningful web experiences.

🛠️ I share tools, experiments, content and digital workflows on GitHub and on my [blog](https://axel-legay.blogspot.com) to help creators and independents build smarter, not harder.

Your sponsorship helps me:
- Keep my content free and open for everyone
- Share resources, templates, and practical ideas
- Develop new tools and experiments around AI, automation, and productivity
- Stay fueled by coffee and cat gifs 🐱☕

If you’ve found value in my work or want to support the indie tech ecosystem — feel free to sponsor me. Even a small gesture means a lot!

Thank you 🙌
